// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaBsl-KhEo0JJFNv7uqxiy7x17CHPSnXI',
    appId: '1:70607372649:web:f182a3fb70b53d7f07fdf8',
    messagingSenderId: '70607372649',
    projectId: 'upgrade-df66a',
    authDomain: 'upgrade-df66a.firebaseapp.com',
    storageBucket: 'upgrade-df66a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRV6m2z4w_We6Z4z_lvPFnLNOJ_vufKDs',
    appId: '1:70607372649:android:596ebef1811798ec07fdf8',
    messagingSenderId: '70607372649',
    projectId: 'upgrade-df66a',
    storageBucket: 'upgrade-df66a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZkcrWhcuUIY5e_2Mvoxk15Cae0cTmmIA',
    appId: '1:70607372649:ios:1d24b85c6f80fa2707fdf8',
    messagingSenderId: '70607372649',
    projectId: 'upgrade-df66a',
    storageBucket: 'upgrade-df66a.firebasestorage.app',
    iosClientId: '70607372649-ltgkgegl5uonv31qkqv4518p294lrbm4.apps.googleusercontent.com',
    iosBundleId: 'com.example.upgrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZkcrWhcuUIY5e_2Mvoxk15Cae0cTmmIA',
    appId: '1:70607372649:ios:1d24b85c6f80fa2707fdf8',
    messagingSenderId: '70607372649',
    projectId: 'upgrade-df66a',
    storageBucket: 'upgrade-df66a.firebasestorage.app',
    iosClientId: '70607372649-ltgkgegl5uonv31qkqv4518p294lrbm4.apps.googleusercontent.com',
    iosBundleId: 'com.example.upgrade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaBsl-KhEo0JJFNv7uqxiy7x17CHPSnXI',
    appId: '1:70607372649:web:191ee8e8af0af58907fdf8',
    messagingSenderId: '70607372649',
    projectId: 'upgrade-df66a',
    authDomain: 'upgrade-df66a.firebaseapp.com',
    storageBucket: 'upgrade-df66a.firebasestorage.app',
  );
}
